#Play settings
[Play]
	#Defines the stage at which the OneBlock should start with. Defaults to oneblock:00
	StartingStage = "oneblock:00"
	#If true, the OneBlock will also use the entries from previous stages.
	UsePreviousStagesForEntries = false
